name: AirBnB CLI

on:
  push:
    branches:
      - 'main'
      - 'wip**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install pycodestyle
        run: |
          python -m pip install --upgrade pip
          pip install pycodestyle==2.8.*
      - name: Run Tests
        run: |
          pycodestyle --filename=*.py, */*.py
          python3 -m unittest discover tests

